"apiVersion": "argoproj.io/v1alpha1"
"kind": "Application"
"metadata":
  "name": "argocd"
  "namespace": "argocd"
"spec":
  "destination":
    "namespace": "argocd"
    "server": "https://kubernetes.default.svc"
  "project": "default"
  "source":
    "chart": "argo-cd"
    "helm":
      "parameters":
      - "name": "server.rbacConfig.policy\\.csv"
        "value": |
          g, administrators, role:admin
      - "name": "server.ingress.tls[0].hosts[0]"
        "value": "argocd.swiss-army-kube.swiss.sak.ninja"
      - "name": "server.ingress.hosts[0]"
        "value": "argocd.swiss-army-kube.swiss.sak.ninja"
      - "name": "server.ingress.tls[0].secretName"
        "value": "argocd-swiss-army-kube.swiss.sak.ninja-tls"
      - "name": "server.ingress.annotations.nginx\\.ingress\\.kubernetes\\.io/ssl-redirect"
        "value": "false"
      - "name": "configs.knownHosts.data.ssh_known_hosts"
        "value": ""
      - "name": "configs.secret.bitbucketServerSecret"
        "value": ""
      - "name": "configs.secret.bitbucketUUID"
        "value": ""
      - "name": "configs.secret.createSecret"
        "value": "true"
      - "name": "configs.secret.githubSecret"
        "value": ""
      - "name": "configs.secret.gitlabSecret"
        "value": ""
      - "name": "configs.secret.gogsSecret"
        "value": ""
      - "name": "dex.enabled"
        "value": "false"
      - "name": "global.securityContext.fsGroup"
        "value": "999"
      - "name": "installCRDs"
        "value": "false"
      - "name": "kubeVersionOverride"
        "value": "1.18"
      - "name": "repoServer.env[0].name"
        "value": "AWS_DEFAULT_REGION"
      - "name": "repoServer.env[0].value"
        "value": "eu-north-1"
      - "name": "repoServer.env[1].name"
        "value": "HELM_PLUGINS"
      - "name": "repoServer.env[1].value"
        "value": "/custom-tools/helm-plugins/"
      - "name": "repoServer.env[2].name"
        "value": "HELM_SECRETS_SOPS_PATH"
      - "name": "repoServer.env[2].value"
        "value": "/custom-tools/sops"
      - "name": "repoServer.env[3].name"
        "value": "HELM_SECRETS_VALS_PATH"
      - "name": "repoServer.env[3].value"
        "value": "/custom-tools/vals"
      - "name": "repoServer.env[4].name"
        "value": "HELM_SECRETS_KUBECTL_PATH"
      - "name": "repoServer.env[4].value"
        "value": "/custom-tools/kubectl"
      - "name": "repoServer.env[5].name"
        "value": "HELM_SECRETS_CURL_PATH"
      - "name": "repoServer.env[5].value"
        "value": "/custom-tools/curl"
      - "name": "repoServer.initContainers[0].args[0]"
        "value": "wget -O kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.2.0/kustomize_3.2.0_linux_amd64
          && chmod +x kustomize && mv kustomize /custom-binaries"
      - "name": "repoServer.initContainers[0].command[0]"
        "value": "sh"
      - "name": "repoServer.initContainers[0].command[1]"
        "value": "-c"
      - "name": "repoServer.initContainers[0].image"
        "value": "alpine:3.15"
      - "name": "repoServer.initContainers[0].name"
        "value": "download-kustomize"
      - "name": "repoServer.initContainers[0].volumeMounts[0].mountPath"
        "value": "/custom-binaries"
      - "name": "repoServer.initContainers[0].volumeMounts[0].name"
        "value": "custom-binaries"
      - "name": "repoServer.initContainers[1].args[0]"
        "value": |
          mkdir -p /custom-tools/helm-plugins
          wget -qO- https://github.com/jkroepke/helm-secrets/releases/download/v${HELM_SECRETS_VERSION}/helm-secrets.tar.gz | tar -C /custom-tools/helm-plugins -xzf-;
          wget -qO /custom-tools/sops https://github.com/mozilla/sops/releases/download/v${SOPS_VERSION}/sops-v${SOPS_VERSION}.linux
          wget -qO /custom-tools/kubectl https://dl.k8s.io/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl
          chmod +x /custom-tools/*
      - "name": "repoServer.initContainers[1].command[0]"
        "value": "sh"
      - "name": "repoServer.initContainers[1].command[1]"
        "value": "-ec"
      - "name": "repoServer.initContainers[1].env[0].name"
        "value": "HELM_SECRETS_VERSION"
      - "name": "repoServer.initContainers[1].env[0].value"
        "value": "3.15.0"
      - "name": "repoServer.initContainers[1].env[1].name"
        "value": "KUBECTL_VERSION"
      - "name": "repoServer.initContainers[1].env[1].value"
        "value": "1.22.13"
      - "name": "repoServer.initContainers[1].env[2].name"
        "value": "VALS_VERSION"
      - "name": "repoServer.initContainers[1].env[2].value"
        "value": "0.18.0"
      - "name": "repoServer.initContainers[1].env[3].name"
        "value": "SOPS_VERSION"
      - "name": "repoServer.initContainers[1].env[3].value"
        "value": "3.7.3"
      - "name": "repoServer.initContainers[1].image"
        "value": "alpine:latest"
      - "name": "repoServer.initContainers[1].name"
        "value": "download-tools"
      - "name": "repoServer.initContainers[1].volumeMounts[0].mountPath"
        "value": "/custom-tools"
      - "name": "repoServer.initContainers[1].volumeMounts[0].name"
        "value": "custom-tools"
      - "name": "repoServer.serviceAccount.annotations.eks\\.amazonaws\\.com/role-arn"
        "value": "arn:aws:iam::641456973426:role/swiss-army-kube_argocd"
      - "name": "repoServer.serviceAccount.create"
        "value": "true"
      - "name": "repoServer.serviceAccount.name"
        "value": "argocd-repo-server"
      - "name": "repoServer.volumeMounts[0].mountPath"
        "value": "/custom-binaries"
      - "name": "repoServer.volumeMounts[0].name"
        "value": "custom-binaries"
      - "name": "repoServer.volumeMounts[0].subPath"
        "value": "kustomize"
      - "name": "repoServer.volumeMounts[1].mountPath"
        "value": "/custom-tools"
      - "name": "repoServer.volumeMounts[1].name"
        "value": "custom-tools"
      - "name": "repoServer.volumes[0].name"
        "value": "custom-binaries"
      - "name": "repoServer.volumes[1].name"
        "value": "custom-tools"
      - "name": "server.config.helm\\.valuesFileSchemes"
        "value": "secrets"
      - "name": "server.config.kustomize\\.path\\.v3\\.2\\.0"
        "value": "/custom-binaries"
      - "name": "server.config.repositories"
        "value": |+
          - url: https://github.com/wallhided/swiss-army-kube
            usernameSecret:
              name: argocd-repo-credentials-secret
              key: username
            passwordSecret:
              name: argocd-repo-credentials-secret
              key: password

      - "name": "server.extraArgs[0]"
        "value": "--insecure"
      - "name": "server.ingress.enabled"
        "value": "true"
      - "name": "server.ingress.paths[0]"
        "value": "/"
      - "name": "server.rbacConfig.policy\\.default"
        "value": "role:readonly"
      - "name": "server.service.type"
        "value": "ClusterIP"
      "values": |
        "configs":
          "secret":
            "argocdServerAdminPassword": "ENC:AQICAHgLyKkfKxS84tXFDYhlyyaAim1Ixcdsn6bCdCs9DsPXawHH90s5FgYz9ce2l4ic05RrAAAAcjBwBgkqhkiG9w0BBwagYzBhAgEAMFwGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMNcMcVECQ+H8qv0rRAgEQgC9g+/iLxV8RUk+HQtCRHDkQUCmX4YP1Zvnd45X+5bZ8KJBAqEkesVnonpKBih/plg=="
    "repoURL": "https://argoproj.github.io/argo-helm"
    "targetRevision": "5.16.13"
  "syncPolicy":
    "automated":
      "prune": true
      "selfHeal": true
