"apiVersion": "argoproj.io/v1alpha1"
"kind": "Application"
"metadata":
  "name": "hashicorp-vault"
  "namespace": "vault"
"spec":
  "destination":
    "namespace": "default"
    "server": "https://kubernetes.default.svc"
  "project": "default"
  "source":
    "chart": "vault"
    "helm":
      "parameters":
      - "name": "rbac.create"
        "value": "true"
      - "name": "resources.limits.cpu"
        "value": "100m"
      - "name": "resources.limits.memory"
        "value": "300Mi"
      - "name": "resources.requests.cpu"
        "value": "100m"
      - "name": "resources.requests.memory"
        "value": "300Mi"
    "repoURL": "https://helm.releases.hashicorp.com"
    "targetRevision": "0.17.0"
  "syncPolicy":
    "automated":
      "prune": true
      "selfHeal": true
