"apiVersion": "argoproj.io/v1alpha1"
"kind": "Application"
"metadata":
  "name": "hashicorp-vault"
  "namespace": "argocd"
"spec":
  "destination":
    "namespace": "kube-system"
    "server": "https://kubernetes.default.svc"
  "project": "default"
  "source":
    "chart": "vault"
    "helm":
      "parameters":
      - "name": "server.standalone.config"
        "value": |
          listener "tcp" {
            tls_disable = 1
            address = "[::]:8200"
            cluster_address = "[::]:8201"
          }

          storage "s3" {
            access_key = "AKIAVXXFWJEG63536HXS"
            secret_key = "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"
            bucket     = "sak-vault-test-bucket"
            region     = "eu-north-1"
          }
    "repoURL": "https://helm.releases.hashicorp.com"
    "targetRevision": "0.17.0"
  "syncPolicy":
    "automated":
      "prune": true
      "selfHeal": true
