"apiVersion": "argoproj.io/v1alpha1"
"kind": "Application"
"metadata":
  "name": "hashicorp-vault"
  "namespace": "argocd"
"spec":
  "destination":
    "namespace": "vault"
    "server": "https://kubernetes.default.svc"
  "project": "default"
  "source":
    "chart": "vault"
    "helm":
      "parameters":
      - "name": "server.standalone.config"
        "value": |
          ui = true
          listener "tcp" {
            tls_disable = 1
            address = "[::]:8200"
            cluster_address = "[::]:8201"
          }

          storage "file" {
            path = "/vault/data"
          }
      - "name": "server.volumes[0].name"
        "value": "efs"
      - "name": "server.volumes[0].persistentVolumeClaim.claimName"
        "value": "efs-pvc"
    "repoURL": "https://helm.releases.hashicorp.com"
    "targetRevision": "0.17.0"
  "syncPolicy":
    "automated":
      "prune": true
      "selfHeal": true
