"apiVersion": "argoproj.io/v1alpha1"
"kind": "Application"
"metadata":
  "name": "hashicorp-vault"
  "namespace": "argocd"
"spec":
  "destination":
    "namespace": "vault"
    "server": "https://kubernetes.default.svc"
  "project": "default"
  "source":
    "chart": "vault"
    "helm":
      "parameters": []
    "repoURL": "https://helm.releases.hashicorp.com"
    "targetRevision": "0.17.0"
  "syncPolicy":
    "automated":
      "prune": true
      "selfHeal": true
